#User operation
---
- name: Create User,add to group,delete user
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Create a new user
      user:
        name: raghu
        password: "{{'raghu'| password_hash('sha512')}}"
        state: present

#Create a new user with the name 'new user' and set the password
    - name: Add a existing user to ec2-user
      user:
        name: raghu
        groups: ec2-user
        append: yes

#Add the existing user 'existing user ' to the group 'group name'

    - name: Remove a user from a group
      user:
        name: raghu
        state: absent

#Remove the existing user 'existing user' from the remote host
