#using apt,yum,dnf,homebrew for installing Maven
#Gather_facts is required  for this condition package manager type
---
- name: Install Apache Maven
  hosts: all
  become: true
  tasks:
    - name: Update Os cache for(UBUNTU)
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Install Maven for (Ubuntu)
      apt:
        name: maven
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Install Maven for(RedHat/CentOs/AmazonLinux)
      yum:
        name: maven
        state: present
      when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
    
    - name: Execute Maven Version command
      command: mvn --version
      register: maven_version_details
      
    - name: Display Register Output
      debug:
        var: maven_version_details.stdout_lines 

