---
- name: Install Git if not present and clone repositories
  hosts: all
  become: true
  tasks:
    - name: check if git is installed
      command: git --version
      register: git_check
      ignore_errors: true

    - name: Install Git
      package:
        name: git
        state: present
      when: git_check.rc!= 0


    - name: clone the repository
      become_user: ansible
      become: true
      git:
        repo: https://github.com/AcAvinash/maven-web-app.git
        dest: /home/ansible/maven-web-app
