---
- name: Service Operations List
  hosts: webservers
  become: true
  tasks:
    - name: Start Services
      service:
        name: httpd
        state: started
#Start the httpd Service
    - name: Stop Services
      service:
        name: httpd
        state: stopped
#Stop the httpd Service
    - name: Enable Services
      service:
        name: httpd
        enabled: true
#Enable the httpd service to start on boot
    - name: Restart Services
      service:
        name: httpd
        state: restarted

#Restart the httpd service